version: "3.0"

services:
  database:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: wikiGo
      MYSQL_USER: user
      MYSQL_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - ./data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    depends_on:
      - database
    ports:
      - 8090:80
    environment:
      PMA_HOST: database
      PMA_USER: root
      PMA_PASSWORD: admin

  swagger:
    image: swaggerapi/swagger-ui
    ports:
    - 8085:8080
    volumes:
    - ./documentation:/documentation
    environment:
      SWAGGER_JSON: /documentation/swagger.json
      BASE_URL: /documentation/api/v1

  api:
    image: golang:1.6.1-alpine
    volumes:
    - .~/go:/usr/src/wiki
    environment:
      GOOS: linux/amd64
    working_dir: /usr/src/wiki/go/github.com/Wiki-Go
    command: go run main.go
    ports:
      - 8080:8080