version: "3.6"

services:
  database:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: wikiGo
      MYSQL_USER: user
      MYSQL_PASSWORD: CvUuM6YK3YVveTYc2McSUvkSxRRkFEJn
    ports:
      - 3306:3306
    volumes:
      - ./data:/var/lib/mysql
    networks:
      backend:

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    depends_on:
      - database
    ports:
      - 8090:80
    environment:
      PMA_HOST: database
      PMA_USER: root
      PMA_PASSWORD: admin
    networks:
      backend:

  swagger:
    image: swaggerapi/swagger-ui
    ports:
    - 8085:8080
    volumes:
    - ./documentation:/documentation
    environment:
      SWAGGER_JSON: /documentation/swagger.json
      BASE_URL: /documentation/api/v1

  wiki:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - database
    environment:
      DATABASE_URL: database
      JWT_SECRET: "QgTPVshDVPqqcNMvinBd8vWhGJ8i7udr"
      DB_PASSWORD: "CvUuM6YK3YVveTYc2McSUvkSxRRkFEJn"
      DB_USER: "user"
      FRONT_URL: "http://localhost"
      DOCUMENTATION_URL: "http://localhost:8085"
      PORT: ":8080"
    links:
      - database
    ports:
    - 8080:8080
    networks:
     backend:

networks:
  backend:
    driver: bridge
